In [1]:
from sqlalchemy import create_engine, MetaData, Table
import json
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
db_url = "mysql+pymysql://maint:strangle.explode.sprout.underfeed.yo-yo@cmlpsiturk.compmemlab.org:3306/psiturk"
table_name = "JOR"

In [4]:
data_column_name = 'datastring'

# boilerplace sqlalchemy setup
engine = create_engine(db_url)
metadata = MetaData()
metadata.bind = engine
table = Table(table_name, metadata, autoload=True)

# make a query and loop through
s = table.select()

In [5]:
rows = s.execute()

# Status codes
NOT_ACCEPTED = 0
ALLOCATED = 1
STARTED = 2
COMPLETED = 3
SUBMITTED = 4
CREDITED = 5
QUITEARLY = 6
BONUSED = 7

In [6]:
data = []

#status codes of subjects who completed experiment
statuses = [3,4,5,7]
# statuses=[0,1,2,3,4,5,6,7]

# if you have workers you wish to exclude, add them here
exclude = [] 

conditions = []
version = '2.1.1'

for row in rows:
    # only use subjects who completed experiment and aren't excluded
    if (row['status'] in statuses) and (row['uniqueid'] not in exclude) and (row['codeversion'] == version):
        conditions.append({
                'uniqueid': row['uniqueid'],
                'beginhit': row['beginhit'],
                'endhit': row['endhit'],
                'status': row['status'],
                'counterbalance': row['counterbalance'],
                'workerid': row['workerid'],
                'codeversion': row['codeversion']
            })
        data.append(row[data_column_name])

In [7]:
condition_frame = pd.DataFrame(conditions)
condition_frame.sort_values('beginhit')

,uniqueid,beginhit,endhit,status,counterbalance,workerid,codeversion
133,A206WLS4KMBH86:3EKVH9QMEZB5BYPK0XRDUQX9TJL2DT,2022-09-28 15:23:46,2022-09-28 15:51:02,4,3,A206WLS4KMBH86,2.1.1
149,A24MI8I7ZUS3HQ:3TXWC2NHN0XMD7T1IW1HZCRN0S4S94,2022-09-28 15:24:09,2022-09-28 16:57:42,4,93,A24MI8I7ZUS3HQ,2.1.1
73,A1HSEVGZBWJUPH:3VHP9MDGRORF70VIOWB9U39GHNDFCP,2022-09-28 15:24:41,2022-09-28 15:59:26,4,81,A1HSEVGZBWJUPH,2.1.1
278,A3D4ZHM3ABM5Z3:3G5W44VEU8P34Y31RTYP07M0NBMKG6,2022-09-28 15:25:45,2022-09-28 15:42:40,4,80,A3D4ZHM3ABM5Z3,2.1.1
59,A1F8F956ETH1TA:3YMU66OBIOFC282TL8VSNF68VUIHGZ,2022-09-28 15:27:40,2022-09-28 15:55:11,4,12,A1F8F956ETH1TA,2.1.1
...,...,...,...,...,...,...,...
66,A1GEO1VUUQQ9K2:3COPXFW7XCJ9HBW0UCOCUG0SQPMPK4,2022-10-17 16:12:18,2022-10-17 16:32:04,4,3,A1GEO1VUUQQ9K2,2.1.1
321,A3UE8ANAIM7F15:3YT88D1N0952AMRDWER5HDXRLU33KH,2022-10-17 16:33:01,2022-10-17 17:15:47,4,8,A3UE8ANAIM7F15,2.1.1
182,A2G2T6EMXAOKMS:3S06PH7KSSBYMD7OHTRZP7N432O1D8,2022-10-17 19:10:51,2022-10-17 19:39:53,4,54,A2G2T6EMXAOKMS,2.1.1
377,AKE4AYF86KJVU:37C0GNLMHGATTZ8LNZ3GK3ELBD5D6J,2022-10-17 19:20:40,2022-10-17 21:00:44,4,86,AKE4AYF86KJVU,2.1.1
174,A2DQ0OE2TBY9E0:36AHBNMV1SJVCJIRTIY83UYEAN2DYN,2022-10-17 19:34:45,2022-10-17 20:06:12,4,24,A2DQ0OE2TBY9E0,2.1.1

In [8]:
condition_frame['uniqueid']

0      A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74
1      A1122EUMFXHF38:3KB8R4ZV1FE2BVZ7LGLW143A17IBGZ
2      A116QUKBGZ6DLC:37M28K1J0RK7JNKGN86336BKBHBJAD
3       A1198W1SPF1R4:3QEMNNSB2Y6CXZMQ6988QHEH5P9D73
4      A121YWZJNUUZRJ:3IXQG4FA2U5NWLCZ7AFM9NHNXUNB98
                           ...
423     AXGQ4AW54L9TM:3L70J4KAZHTUG1KODCKS08G76XEADQ
424     AXVGIRLNPA6Z2:3R2UR8A0IBNXGBJ6EVQMVA34B4MXOM
425     AXYNQIL0J2BP2:3M81GAB8A1QTOKTLOCQ8VI7C7UPQB7
426     AY7M9MOLNXIIK:3CPLWGV3MP6PXU1WA0KV0IHHERZ9N9
427     AZXNPVVLWKK1V:3RRCEFRB7NJMZF6NQFJVSF67B29B4C
Name: uniqueid, Length: 428, dtype: object

In [9]:
# Now we have all participant datastrings in a list.
# Let's make it a bit easier to work with:

# parse each participant's datastring as json object
# and take the 'data' sub-object
subject_data = []
for subject_json in data:
    try:
        subject_dict = json.loads(subject_json)
        subject_data.append(subject_dict['data'])
    except:
        continue

In [10]:
# insert uniqueid field into trialdata in case it wasn't added
# in experiment:
for part in subject_data:
    for record in part:
        record['trialdata']['uniqueid'] = record['uniqueid']

In [11]:
# flatten nested list so we just have a list of the trialdata recorded
# each time psiturk.recordTrialData(trialdata) was called.
trialdata = []
for part in subject_data:
    for record in part:
        trialdata.append(record['trialdata'])

In [12]:
# Put all subjects' trial data into a dataframe object from the
# 'pandas' python library: one option among many for analysis
data_frame = pd.DataFrame(trialdata)

# Print how many subj before eliminations:
print("Subjects before eliminations: ", len(data_frame['uniqueid'].unique()))

Subjects before eliminations:  428

In [13]:
# Remove subjects that admitted to writing down studied words
were_distracted = 0
took_notes = 0
both = 0

for i in data_frame['uniqueid'].unique():
    df = data_frame[data_frame['uniqueid'] == i]
    
    # get whether or not indicated distracted / wrote notes
    distracted = (df['responses'].str.startswith("{\"distracted\":\"Yes\"}", na=False) == True).sum()
    wrote_notes = (df['responses'].str.startswith("{\"wrote_notes\":\"Yes\"}", na=False) == True).sum()
    
    # increment counters appropriately
    if distracted and wrote_notes:
        both += 1
        data_frame = data_frame.drop(df.index)
    elif distracted:
        were_distracted += 1
        data_frame = data_frame.drop(df.index)
    elif wrote_notes:
        took_notes += 1
        data_frame = data_frame.drop(df.index)
    
print("individuals distracted, but did not take notes: ", were_distracted)
print("Individuals who took notes, but were not distracted: ", took_notes)
print("Individuals who did both: ", both)

# Print how many subj after eliminations
print("Subjects remaining: ", len(data_frame['uniqueid'].unique()))

individuals distracted, but did not take notes:  5
Individuals who took notes, but were not distracted:  35
Individuals who did both:  17
Subjects remaining:  371

In [14]:
def getComparisonAccuracy(df, comp1, comp2):
    left_correct = len(df[df['left_comp_type'] == comp1][df['right_comp_type'] == comp2][df['chosen_side'] == df['correct_side']])
    right_correct = len(df[df['left_comp_type'] == comp2][df['right_comp_type'] == comp1][df['chosen_side'] == df['correct_side']])
    left = len(df[df['left_comp_type'] == comp1][df['right_comp_type'] == comp2])
    right = len(df[df['left_comp_type'] == comp2][df['right_comp_type'] == comp1])
    return (left_correct + right_correct)/(left + right)

def getFirstDistanceAccuracy(df, dist):
    second_distances = [6, 8, 10, 16, 22, 30, 40]
    total = 0
    num = 0
    for i in second_distances:
        if (i > dist):
            total += getComparisonAccuracy(df, dist, i)
            num += 1
    return total / num

def getSecondDistanceAccuracy(df, dist):
    first_distances = [4, 6, 8, 10, 14, 18, 22, 28, 34]
    total = 0
    num = 0
    for i in first_distances:
        if (i < dist):
            total += getComparisonAccuracy(df, dist, i)
            num += 1
    return total / num

def getOverallAccuracy(df):
    first_distances = [4, 6, 8, 10, 14, 18, 22, 28, 34]
    total = 0
    for i in first_distances:
        total += getFirstDistanceAccuracy(df, i)
    return total / len(first_distances)

In [23]:
data_frame_2_1_1 = data_frame
data_frame

,rt,responses,type,trial_type,trial_index,time_elapsed,internal_node_id,uniqueid,stimulus,key_press,...,left_word_test,right_word_test,chosen_side,comparison_type,left_comp_type,right_comp_type,correct_side,question_order,required,further_experiments
0,14959.0,"{""name"":""Maia""}",NAME,survey-html-form,0,14980,0.0-0.0-0.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3699.0,NaN,NaN,html-keyboard-response,1,18918,0.0-1.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,Welcome to the <strong>Judgment of Recency</st...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,129585.0,NaN,NaN,html-keyboard-response,2,148741,0.0-2.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,"<p>In this experiment, you will encounter a nu...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,48232.0,NaN,NaN,html-button-response,3,197192,0.0-3.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,<p style = 'text-align:left;'>Dear Participant...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8246.0,NaN,NaN,html-button-response,4,205459,0.0-5.0-0.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,<p class='inst-justified'>According to Wikiped...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115642,3473.6,"{""education"":""Bachelor's degree""}",NaN,survey-dropdown,274,1166195,0.0-255.0,AZXNPVVLWKK1V:3RRCEFRB7NJMZF6NQFJVSF67B29B4C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
115643,3677.5,"{""marital"":""Married/Domestic Partnership""}",NaN,survey-dropdown,275,1169877,0.0-256.0,AZXNPVVLWKK1V:3RRCEFRB7NJMZF6NQFJVSF67B29B4C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
115644,4424.2,"{""wrote_notes"":""No""}",NaN,survey-multi-choice,276,1174308,0.0-257.0,AZXNPVVLWKK1V:3RRCEFRB7NJMZF6NQFJVSF67B29B4C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
115645,4674.8,"{""distracted"":""No""}",NaN,survey-multi-choice,277,1178988,0.0-258.0,AZXNPVVLWKK1V:3RRCEFRB7NJMZF6NQFJVSF67B29B4C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
115646,6201.9,NaN,NaN,html-button-response,278,1185195,0.0-259.0,AZXNPVVLWKK1V:3RRCEFRB7NJMZF6NQFJVSF67B29B4C,"<div style=""text-align:center;"">Congratulation...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,yes

In [24]:
accuracies = []
for i in data_frame_2_1_1['uniqueid'].unique():
    df = data_frame_2_1_1[data_frame_2_1_1['uniqueid'] == i]
    accuracies.append(getOverallAccuracy(df))

In [16]:
criteria_count = 0
for i in data_frame_2_1_1['uniqueid'].unique():
    
    df = data_frame_2_1_1[data_frame_2_1_1['uniqueid'] == i]
    if (getOverallAccuracy(df) < 0.6):
        data_frame_2_1_1 = data_frame_2_1_1.drop(df.index)
        criteria_count += 1

print("Subject who did not make the criteria: ", criteria_count)

# Print how many subj after eliminations
print("Subjects remaining: ", len(data_frame_2_1_1['uniqueid'].unique()))

Subject who did not make the criteria:  277
Subjects remaining:  94

In [17]:
%store data_frame_2_1_1

Stored 'data_frame_2_1_1' (DataFrame)

In [18]:
data_frame_2_1_1

,rt,responses,type,trial_type,trial_index,time_elapsed,internal_node_id,uniqueid,stimulus,key_press,...,left_word_test,right_word_test,chosen_side,comparison_type,left_comp_type,right_comp_type,correct_side,question_order,required,further_experiments
0,14959.0,"{""name"":""Maia""}",NAME,survey-html-form,0,14980,0.0-0.0-0.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3699.0,NaN,NaN,html-keyboard-response,1,18918,0.0-1.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,Welcome to the <strong>Judgment of Recency</st...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,129585.0,NaN,NaN,html-keyboard-response,2,148741,0.0-2.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,"<p>In this experiment, you will encounter a nu...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,48232.0,NaN,NaN,html-button-response,3,197192,0.0-3.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,<p style = 'text-align:left;'>Dear Participant...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8246.0,NaN,NaN,html-button-response,4,205459,0.0-5.0-0.0,A102WSFN62OS6I:3BWI6RSP7HGHP50Q24JSWZW2591E74,<p class='inst-justified'>According to Wikiped...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113210,6860.0,"{""education"":""Bachelor's degree""}",NaN,survey-dropdown,263,3975366,0.0-255.0,AWJKR5GA7BS7V:3L0KT67Y8FN1E819Q8TXYTKEBZEYSM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
113211,7242.0,"{""marital"":""Married/Domestic Partnership""}",NaN,survey-dropdown,264,3982614,0.0-256.0,AWJKR5GA7BS7V:3L0KT67Y8FN1E819Q8TXYTKEBZEYSM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
113212,10523.0,"{""wrote_notes"":""No""}",NaN,survey-multi-choice,265,3993144,0.0-257.0,AWJKR5GA7BS7V:3L0KT67Y8FN1E819Q8TXYTKEBZEYSM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
113213,7468.0,"{""distracted"":""No""}",NaN,survey-multi-choice,266,4000616,0.0-258.0,AWJKR5GA7BS7V:3L0KT67Y8FN1E819Q8TXYTKEBZEYSM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[0],NaN,NaN
113214,6901.0,NaN,NaN,html-button-response,267,4007527,0.0-259.0,AWJKR5GA7BS7V:3L0KT67Y8FN1E819Q8TXYTKEBZEYSM,"<div style=""text-align:center;"">Congratulation...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,yes